// Los catorce vectores de `SPEC-calculo.md` §5 escritos como `Inputs` del motor real (copiados de
// `docs/verify-vectors.mjs`, la implementación de referencia). Existen para que el generador de
// comidas y el PDF se prueben contra la salida de `calcular()` y no contra un `Resultado`
// fabricado a mano: los fallos de low-carb, de preferencia en las alternativas y de límites de
// ración solo aparecen encadenando motor → menús → PDF.
import type { Inputs, InputEntrenamiento } from '../../engine/types'

const BASE: Pick<
  Inputs,
  | 'clima_caluroso'
  | 'embarazo_lactancia'
  | 'condiciones'
  | 'fecha_inicio'
  | 'peso_objetivo'
  | 'somatotipo'
  | 'ritmo'
  | 'preferencia'
  | 'cribado_tca'
> = {
  clima_caluroso: false,
  embarazo_lactancia: false,
  condiciones: [],
  fecha_inicio: '2026-09-07',
  peso_objetivo: null,
  somatotipo: null,
  ritmo: 'moderado',
  preferencia: 'omnivoro',
  cribado_tca: null,
}

const ent = (o: Partial<InputEntrenamiento> = {}): InputEntrenamiento => ({
  tipo: 'ninguno',
  dias_semana: 0,
  minutos_sesion: 0,
  intensidad: 'media',
  experiencia: 'novato',
  momento: null,
  ...o,
})

export interface VectorMenu {
  n: string
  descripcion: string
  inputs: Inputs
}

export const VECTORES: VectorMenu[] = [
  {
    n: '1',
    descripcion: 'Hombre 32, sobrepeso ligero, fuerza, perder grasa, 4 comidas',
    inputs: {
      ...BASE,
      sexo: 'hombre',
      edad: 32,
      altura_cm: 178,
      peso_kg: 84,
      grasa: { metodo: 'desconocido' },
      somatotipo: { q1: 'media', q2: 'moderada', q3: 'moderada', q4: 'atletico' },
      actividad_diaria: 'ligero',
      entrenamiento: ent({
        tipo: 'fuerza',
        dias_semana: 4,
        minutos_sesion: 60,
        intensidad: 'media',
        experiencia: 'intermedio',
        momento: 'tarde',
      }),
      objetivo: 'perder',
      ritmo: 'moderado',
      n_comidas: 4,
    },
  },
  {
    n: '2',
    descripcion: 'Mujer 28, medidas US Navy, recomposición, vegetariana, cribado TCA',
    inputs: {
      ...BASE,
      sexo: 'mujer',
      edad: 28,
      altura_cm: 165,
      peso_kg: 60,
      grasa: { metodo: 'medidas', cuello_cm: 32, cintura_cm: 72, cadera_cm: 96 },
      somatotipo: { q1: 'fina', q2: 'poca', q3: 'moderada', q4: 'delgado' },
      actividad_diaria: 'sedentario',
      entrenamiento: ent({
        tipo: 'cardio',
        dias_semana: 3,
        minutos_sesion: 45,
        intensidad: 'media',
        experiencia: 'novato',
        momento: 'manana',
      }),
      objetivo: 'recomposicion',
      ritmo: 'moderado',
      preferencia: 'vegetariano',
      n_comidas: 3,
      condiciones: ['tca'],
    },
  },
  {
    n: '3',
    descripcion: 'Hombre 45, obesidad II, sedentario, ritmo agresivo, peso objetivo 85 kg',
    inputs: {
      ...BASE,
      sexo: 'hombre',
      edad: 45,
      altura_cm: 172,
      peso_kg: 105,
      grasa: { metodo: 'desconocido' },
      somatotipo: { q1: 'ancha', q2: 'mucha', q3: 'moderada', q4: 'robusto' },
      actividad_diaria: 'sedentario',
      entrenamiento: ent(),
      objetivo: 'perder',
      ritmo: 'agresivo',
      peso_objetivo: 85,
      n_comidas: 3,
    },
  },
  {
    n: '4',
    descripcion: 'Mujer 52, obesidad I, estimación visual, "no lo sé", diabetes, 5 comidas',
    inputs: {
      ...BASE,
      sexo: 'mujer',
      edad: 52,
      altura_cm: 160,
      peso_kg: 82,
      grasa: { metodo: 'visual', categoria: 'sobrepeso_visible' },
      actividad_diaria: 'moderado',
      entrenamiento: ent({
        tipo: 'mixto',
        dias_semana: 2,
        minutos_sesion: 45,
        intensidad: 'baja',
        experiencia: 'novato',
        momento: 'mediodia',
      }),
      objetivo: 'no_se',
      ritmo: 'suave',
      preferencia: 'sin_lactosa',
      n_comidas: 5,
      condiciones: ['diabetes'],
    },
  },
  {
    n: '5',
    descripcion: 'Hombre 68, %grasa fiable (Katch-McArdle), mantenimiento, fuerza ligera',
    inputs: {
      ...BASE,
      sexo: 'hombre',
      edad: 68,
      altura_cm: 175,
      peso_kg: 78,
      grasa: { metodo: 'conocido', valor: 24, fuente: 'fiable' },
      somatotipo: { q1: 'media', q2: 'moderada', q3: 'mucha', q4: 'atletico' },
      actividad_diaria: 'ligero',
      entrenamiento: ent({
        tipo: 'fuerza',
        dias_semana: 3,
        minutos_sesion: 45,
        intensidad: 'baja',
        experiencia: 'novato',
        momento: 'manana',
      }),
      objetivo: 'mantener',
      n_comidas: 3,
    },
  },
  {
    n: '6',
    descripcion: 'Mujer 35, delgada, %grasa estimado, gana músculo, peso objetivo 60 kg',
    inputs: {
      ...BASE,
      sexo: 'mujer',
      edad: 35,
      altura_cm: 170,
      peso_kg: 56,
      grasa: { metodo: 'conocido', valor: 21, fuente: 'estimado' },
      somatotipo: { q1: 'fina', q2: 'poca', q3: 'poca', q4: 'delgado' },
      actividad_diaria: 'sedentario',
      entrenamiento: ent({
        tipo: 'fuerza',
        dias_semana: 3,
        minutos_sesion: 60,
        intensidad: 'media',
        experiencia: 'novato',
        momento: 'tarde',
      }),
      objetivo: 'ganar',
      ritmo: 'moderado',
      peso_objetivo: 60,
      n_comidas: 4,
    },
  },
  {
    n: '7',
    descripcion: 'Hombre 40, trabajo físico, low-carb, endomorfo, clima caluroso',
    inputs: {
      ...BASE,
      sexo: 'hombre',
      edad: 40,
      altura_cm: 180,
      peso_kg: 92,
      grasa: { metodo: 'desconocido' },
      somatotipo: { q1: 'ancha', q2: 'mucha', q3: 'moderada', q4: 'robusto' },
      actividad_diaria: 'alto',
      entrenamiento: ent({
        tipo: 'cardio',
        dias_semana: 2,
        minutos_sesion: 40,
        intensidad: 'media',
        experiencia: 'intermedio',
        momento: 'noche',
      }),
      objetivo: 'perder',
      ritmo: 'moderado',
      peso_objetivo: 80,
      preferencia: 'low_carb',
      n_comidas: 3,
      clima_caluroso: true,
    },
  },
  {
    n: '8',
    descripcion: 'Mujer 29, sedentaria, ritmo agresivo, vegana, peso objetivo irreal, 2 comidas',
    inputs: {
      ...BASE,
      sexo: 'mujer',
      edad: 29,
      altura_cm: 162,
      peso_kg: 66,
      grasa: { metodo: 'visual', categoria: 'media' },
      somatotipo: { q1: 'media', q2: 'moderada', q3: 'moderada', q4: 'atletico' },
      actividad_diaria: 'sedentario',
      entrenamiento: ent(),
      objetivo: 'perder',
      ritmo: 'agresivo',
      peso_objetivo: 48,
      preferencia: 'vegano',
      n_comidas: 2,
    },
  },
  {
    n: '9',
    descripcion: 'Hombre 25, ectomorfo, fuerza 5 días, volumen agresivo, 6 comidas',
    inputs: {
      ...BASE,
      sexo: 'hombre',
      edad: 25,
      altura_cm: 185,
      peso_kg: 70,
      grasa: { metodo: 'desconocido' },
      somatotipo: { q1: 'fina', q2: 'poca', q3: 'poca', q4: 'delgado' },
      actividad_diaria: 'sedentario',
      entrenamiento: ent({
        tipo: 'fuerza',
        dias_semana: 5,
        minutos_sesion: 75,
        intensidad: 'alta',
        experiencia: 'novato',
        momento: 'noche',
      }),
      objetivo: 'ganar',
      ritmo: 'agresivo',
      n_comidas: 6,
    },
  },

  // ---- Vectores 10-14: los que pidió la revisión adversaria del motor (docs/verify-vectors.mjs,
  // constante `CASOS`). Sin ellos, el generador de menús, la lista de la compra y el PDF nunca
  // veían el bucle de factibilidad, el suelo por encima del TDEE, el cap renal ni los ≥ 65 años.
  {
    n: '10',
    descripcion: 'Mujer 30, 150 cm, obesidad y ritmo agresivo — bucle de factibilidad del paso 10',
    inputs: {
      ...BASE,
      sexo: 'mujer',
      edad: 30,
      altura_cm: 150,
      peso_kg: 70,
      grasa: { metodo: 'visual', categoria: 'obesidad_visible' },
      actividad_diaria: 'sedentario',
      entrenamiento: ent(),
      objetivo: 'perder',
      ritmo: 'agresivo',
      n_comidas: 3,
    },
  },
  {
    n: '11',
    descripcion: 'Hombre 25, 195 cm y 8 % de grasa — suelo por encima del TDEE (paso 7)',
    inputs: {
      ...BASE,
      sexo: 'hombre',
      edad: 25,
      altura_cm: 195,
      peso_kg: 100,
      grasa: { metodo: 'conocido', valor: 8, fuente: 'fiable' },
      actividad_diaria: 'sedentario',
      entrenamiento: ent(),
      objetivo: 'perder',
      ritmo: 'moderado',
      n_comidas: 3,
    },
  },
  {
    n: '12',
    descripcion: 'Hombre 35 en el borde exacto de la banda medio — WARN_YA_EN_OBJETIVO',
    inputs: {
      ...BASE,
      sexo: 'hombre',
      edad: 35,
      altura_cm: 180,
      peso_kg: 80,
      grasa: { metodo: 'conocido', valor: 15, fuente: 'estimado' },
      actividad_diaria: 'ligero',
      entrenamiento: ent({
        tipo: 'fuerza',
        dias_semana: 3,
        minutos_sesion: 60,
        intensidad: 'media',
        experiencia: 'intermedio',
        momento: 'tarde',
      }),
      objetivo: 'perder',
      ritmo: 'moderado',
      n_comidas: 4,
    },
  },
  {
    n: '13',
    descripcion: 'Hombre 62 con enfermedad renal e IMC ≥ 30 — sin menú por §3.1',
    inputs: {
      ...BASE,
      sexo: 'hombre',
      edad: 62,
      altura_cm: 170,
      peso_kg: 95,
      grasa: { metodo: 'desconocido' },
      actividad_diaria: 'ligero',
      entrenamiento: ent({
        tipo: 'fuerza',
        dias_semana: 3,
        minutos_sesion: 45,
        intensidad: 'media',
        experiencia: 'novato',
        momento: 'manana',
      }),
      objetivo: 'perder',
      ritmo: 'moderado',
      n_comidas: 3,
      condiciones: ['renal'],
    },
  },
  {
    n: '14',
    descripcion: 'Mujer 70 con objetivo perder — modificadores de edad ≥ 65',
    inputs: {
      ...BASE,
      sexo: 'mujer',
      edad: 70,
      altura_cm: 158,
      peso_kg: 75,
      grasa: { metodo: 'desconocido' },
      actividad_diaria: 'ligero',
      entrenamiento: ent({
        tipo: 'fuerza',
        dias_semana: 2,
        minutos_sesion: 40,
        intensidad: 'baja',
        experiencia: 'novato',
        momento: 'manana',
      }),
      objetivo: 'perder',
      ritmo: 'agresivo',
      n_comidas: 4,
    },
  },
]

/** kcal de la tabla resumen de la §5: si el motor cambia, este test lo detecta antes que nadie. */
export const KCAL_VECTORES: Record<string, number> = {
  '1': 2190,
  '2': 1740,
  '3': 1910,
  '4': 1730,
  '5': 2410,
  '6': 2070,
  '7': 2420,
  '8': 1430,
  '9': 3110,
  '10': 1380,
  '11': 3140,
  '12': 2430,
  '13': 1780,
  '14': 1580,
}
